version: "3.3"

services:
  web:
    image: nginx:latest
    ports:
      - "3600:80"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:7.2-fpm-sockets
    volumes:
      - ./www:/usr/share/nginx/html
